// NOTE DO NOT EDIT THIS FILE!

/** @param {MetaRequirements} meta */
export function setupQuiz (meta) {
  const stdCSS = document.createElement("link");
  stdCSS.rel = "stylesheet";
  stdCSS.href = "/lib/std.css";
  document.head.appendChild(stdCSS);
  const scriptUrl = new URL("/lib/std.js", location.href);
  scriptUrl.searchParams.set("mod", meta.moduleNumber);
  scriptUrl.searchParams.set("json", meta.jsonUrl);
  scriptUrl.searchParams.set("course", meta.course);
  if (meta.loadingMsg) scriptUrl.searchParams.set("load-msg", meta.loadingMsg);
  const scriptElement = document.createElement("script");
  scriptElement.src = scriptUrl;
  scriptElement.type = "module";
  document.head.appendChild(scriptElement);
};
